import numpy as np
print("Reshaping:")
arr=np.arange(1,10)
reshape=np.reshape(arr,(3,3),order='C')
print(reshape) 
print("Original array:",arr)  #Original array wont change
print("Resizing:")
print(np.resize(arr,(4,3)))
print("Original array:",arr)
arr=np.array([[1,2,3],[4,5,6]])
ravel=np.ravel(arr,order='C')
print("Ravel:",ravel)
print(arr.ndim)
print("Original array:",arr)
print("Copying Array:")
copy=arr.copy()
print(copy)
print("View:")
arr_view=arr[:1,1:]
print(arr_view) 
arr1=np.array([[70,10,20],[60,50,40]])
arr_sort=np.sort(arr1,axis=0,kind='quicksort')
print(arr_sort)
dtype= [('name', 'S10'), ('age', int)]
arr = np.array([('John', 30), ('Alice', 25), ('Bob', 35)],
 dtype=dtype)
sorted_arr = np.sort(arr, order='age')
print(sorted_arr)
print("searching:")
arr=np.array([1,2,3,4,5])
indices=np.where(arr>3)
print(indices)
print()
print("Boolean indexing/Filtering:")
arr=np.array([1,2,3,4,5])
filtered_arr=arr[arr%2==0]
print(filtered_arr)
print(arr)
print()
print("Joining:")
A1=np.array([1,2,3])
A2=np.array([4,5,6])
joined_arr=np.concatenate((A1,A2))
print(joined_arr)
print( )
print("np.stack:")
# Create two arrays
array1 = np.array([[1, 2, 3],['a','b','c']])
array2 = np.array([[4, 5, 6],['d','e','f']])
# Stack the arrays along a new axis
stacked_array = np.stack((array1, array2),axis=0)
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nStacked array:")
print(stacked_array)
print()
print("hstack(): & vstack():")
array3=np.hstack((array1,array2))
print("hstack():",array3)
array4=np.vstack((array1,array2))
print("vstack():",array4)
print()
print("Splitting:")
arr=np.array([1,2,3,4,5,6])
sub_arr=np.split(arr,2)
print(sub_arr)
print(sub_arr[1])
print("hsplit(): & vsplit():")
arr = np.array([[1, 2, 3,4],
 [4, 5, 6,7],
 [8, 9,10,11],
 [12,13,14,15]])
h_split=np.hsplit(arr,2)
print(h_split)
v_split=np.vsplit(arr,2)
print(v_split)